### ISSUE TITLE
watchexec-cli 1.20.0 crash on start

### ISSUE THREAD

**Issue by nuclearglow** [watchexec/watchexec#345]
Hello watchexec crew, I am using your extremely useful tool for several months now, but with the new release 1.20.0 I am suddenly running into an error. When running the same command using the previous version (`cargo install watchexec-cli --version 1.19.0`), everything works just fine.

Hope you can help!
Here is the crashlog, a logfile has not been created:

```shell
watchexec --exts ts --watch src --restart --signal SIGINT --clear -vvv --log-file ./watchexec.log 'node --inspect=6969 -r ts-node/register src/cmd/startControl.ts'
thread 'main' panicked at 'Unable to install global subscriber: SetLoggerError(())', /home/nuky/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.11/src/fmt/mod.rs:1201:16
stack backtrace:
   0:     0x5599ca21f41d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5599ca21f41d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5599ca21f41d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5599ca21f41d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5599ca245a0c - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x5599ca2190a1 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x5599ca2210a5 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5599ca2210a5 - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5599ca2210a5 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x5599ca220d59 - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x5599ca2215f2 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
  11:     0x5599ca2214d7 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  12:     0x5599ca21f8d4 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5599ca221209 - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  14:     0x5599c9c4e923 - core::panicking::panic_fmt::h366d3a309ae17c94
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  15:     0x5599c9c4ea13 - core::result::unwrap_failed::hddd78f4658ac7d0f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
  16:     0x5599c9d3fad2 - tracing_subscriber::fmt::init::h455c62996c5d88b6
  17:     0x5599c9ce9390 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb226c4b3e6ec7138
  18:     0x5599c9cbf4ad - std::thread::local::LocalKey<T>::with::h1e84ef08a44bf04a
  19:     0x5599c9c66caa - tokio::park::thread::CachedParkThread::block_on::hbf4e0852b550a551
  20:     0x5599c9c5cf6d - tokio::runtime::thread_pool::ThreadPool::block_on::hbe95c0eb28aa6583
  21:     0x5599c9ca33ac - tokio::runtime::Runtime::block_on::hd3e5b62b9ad30afb
  22:     0x5599c9c7f6de - watchexec::main::h35d8a8869add89c3
  23:     0x5599c9c56a73 - std::sys_common::backtrace::__rust_begin_short_backtrace::hff5367952eb91120
  24:     0x5599c9c749cd - std::rt::lang_start::{{closure}}::h6c8d32b82db78422
  25:     0x5599ca21355e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  26:     0x5599ca21355e - std::panicking::try::do_call::hf2ad5355fcafe775
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  27:     0x5599ca21355e - std::panicking::try::h0a63ac363423e61e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  28:     0x5599ca21355e - std::panic::catch_unwind::h18088edcecb8693a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  29:     0x5599ca21355e - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
  30:     0x5599ca21355e - std::panicking::try::do_call::hda0c61bf3a57d6e6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  31:     0x5599ca21355e - std::panicking::try::hbc940e68560040a9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  32:     0x5599ca21355e - std::panic::catch_unwind::haed0df2aeb3fa368
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  33:     0x5599ca21355e - std::rt::lang_start_internal::h9c06694362b5b80c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  34:     0x5599c9c7f7b2 - main
  35:     0x7f9ea7d63d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  36:     0x7f9ea7d63e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  37:     0x5599c9c4ebc5 - _start
  38:                0x0 - <unknown>
```

```
Version: watchexec-cli 1.20.0 (cargo install watchexec-cli)
rustc 1.61.0 (fe5b13d68 2022-05-18)

                  yyyyy- -yyyyyy+      OS: Ubuntu 22.04 jammy
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.15.0-10033-tuxedo
           .++ .:/++++++/-.+sss/`      Uptime: 7d 10h 49m
         .:++o:  /++++++++/:--:/-      Packages: 2182
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.8.1
       .:+o:+o/.          `+sssoo+/    Resolution: 5360x1440
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 41.4
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme:
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru-dark [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Yaru
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 79G / 1.8T (5%)
           .o:`.syhhhhhhh/.oo++o`      CPU: AMD Ryzen 7 4800H with Radeon Graphics @ 16x 2.9GHz
               /osyyyyyyo++ooo+++/     GPU: AMD RENOIR (LLVM 13.0.1, DRM 3.42, 5.15.0-10033-tuxedo)
                   ````` +oo+++o\:     RAM: 18448MiB / 62211MiB
                          `oo++.
```

**Comment by thomasf** [comment]
I have another at start crash, I was in the middle of work so reverted to the earluer version quickly. Will follow up with proper bug report later this week if the problem persists.


```
...
  2022-06-27T12:12:50.417587Z DEBUG globset: built glob set; 0 literals, 1 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 11 regexes
    at /home/t/.cargo/registry/src/github.com-1ecc6299db9ec823/globset-0.4.9/src/lib.rs:431

thread 'main' panicked at 'Must use `Arg::allow_invalid_utf8` with `_os` lookups', /home/t/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.6/src/parser/matches/arg_matches.rs:1721:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: clap::parser::matches::arg_matches::unwrap_os_string
   3: <clap::parser::matches::arg_matches::Values as core::iter::traits::iterator::Iterator>::next
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   5: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   6: watchexec::filterer::globset::globset::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: tokio::park::thread::CachedParkThread::block_on
  10: tokio::runtime::thread_pool::ThreadPool::block_on
  11: tokio::runtime::Runtime::block_on
  12: watchexec::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  2022-06-27T12:12:50.423345Z TRACE mio::poll: deregistering event source from poller
    at /home/t/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.4/src/poll.rs:652
```

**Comment by passcod** [comment]
Oh, urgh. That second is easy, I'll push a fix asap. That first one, though, not so trivial... do you have a`RUST_LOG` value in your environment?

**Comment by nuclearglow** [comment]
I can confirm everything works fine again with `1.20.2`. Thanks for the quick bugfix, awesome work :-)
