### ISSUE TITLE
panic when trying to watch non-existent folder

### ISSUE THREAD

**Issue by sanga** [watchexec/watchexec#71]
accidentally ran a command from history in the wrong dir, so the dir I wanted to watch didn't exist. Pretty minor bug, it's kind of obvious what happened. Still it might be nicer to print and error and exit rather than panic.

```
RUST_BACKTRACE=1 watchexec --exts=py -w tests "pylint --rcfile=pylintrc tests"
thread 'main' panicked at 'unable to canonicalize "tests": Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:498
   6: core::result::unwrap_failed
   7: watchexec::run::run
   8: watchexec::main
   9: main
  10: __libc_start_main
  11: _start
[1]    2889 abort (core dumped)  RUST_BACKTRACE=1 watchexec --exts=py -w tests "pylint --rcfile=pylintrc tests
```

This is against v 1.8.6 btw

**Comment by batisteo** [comment]
I ran into this as well.
What should be the error message?
`watchexec couldn’t find the `**`tests`**` directory`
or something with a lighter tone maybe?

**Comment by sanga** [comment]
This can now be closed?

**Comment by passcod** [comment]
Ah, yes :)
