### ISSUE TITLE
Unable to spawn process "Argument list too long"

### ISSUE THREAD

**Issue by khepin** [watchexec/watchexec#78]
I'm watching a whole bunch of javascript files during a build so the results can be rsynced in the end to a remote server.
However when doing a full re-build which removes all the node modules (a plentiful of files), then downloads them then starts building, watchexec crashes with the following backtrace:

```
seb$ RUST_BACKTRACE=1 /usr/local/bin/watchexec --no-vcs-ignore -w ~/projects/my/project -- echo "syncing"
syncing
thread 'main' panicked at 'unable to spawn process: Error { repr: Os { code: 7, message: "Argument list too long" } }', src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_new
   4: std::panicking::begin_panic_fmt
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: watchexec::process::spawn
   8: watchexec::run::run
   9: watchexec::main
  10: main
Abort trap: 6
```

**Comment by mattgreen** [comment]
Could you re-run that with the `--verbose` flag?

**Comment by khepin** [comment]
This is what I get:

```
seb$ watchexec --no-vcs-ignore --verbose -- echo "synced"
*** Adding ignore: "**/.DS_Store"
*** Adding ignore: "*.pyc"
*** Adding ignore: "*.swp"
*** Adding ignore: "**/.git/**"
*** Adding ignore: "**/.hg/**"
*** Adding ignore: "**/.svn/**"
*** glob converted to regex: Glob { glob: "**/.git/**", re: "(?-u)^(?:/?|.*/)\\.git(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('g'), Literal('i'), Literal('t'), RecursiveSuffix]) }
*** glob converted to regex: Glob { glob: "**/.hg/**", re: "(?-u)^(?:/?|.*/)\\.hg(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('h'), Literal('g'), RecursiveSuffix]) }
*** glob converted to regex: Glob { glob: "**/.svn/**", re: "(?-u)^(?:/?|.*/)\\.svn(?:/?|/.*)$", opts: GlobOptions { case_insensitive: false, literal_separator: false }, tokens: Tokens([RecursivePrefix, Literal('.'), Literal('s'), Literal('v'), Literal('n'), RecursiveSuffix]) }
*** built glob set; 0 literals, 1 basenames, 2 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 3 regexes
*** Watching "/Users/xyz/projects/abc/abc"
*** Assembled command "sh" "-c" "echo synced"
*** Waiting for filesystem activity
synced
*** Received SIGCHLD
*** Ignoring "/Users/xyz/projects/abc/abc/node_modules/extglob/lib/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/node_modules/vue/src/platforms/weex/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/node_modules/vue/src/platforms/weex/compiler/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/node_modules/vue/src/platforms/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/node_modules/vue/src/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/node_modules/vue/src/compiler/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/node_modules/micromatch/lib/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/node_modules/braces/lib/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/node_modules/nanomatch/lib/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/components/jquery.inputmask/dist/.DS_Store": matched ignore filter
*** Ignoring "/Users/xyz/projects/abc/abc/components/jquery-ui/ui/.DS_Store": matched ignore filter
*** Path updated: PathOp { path: "/Users/xyz/projects/abc/abc/node_modules/indexes-of/.npmignore", op: Some(REMOVE), cookie: None }
*** Waiting for process to exit...
*** Launching child process
*** Assembled command "sh" "-c" "echo synced"
*** Received SIGCHLD
thread 'main' panicked at 'unable to spawn process: Error { repr: Os { code: 7, message: "Argument list too long" } }', src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Abort trap: 6
```

Also, what I could've started with: thanks for making `watchexec`, I find it super useful and I don't need to look up the docs every time I want to use it as I used to do with fswatch!

**Comment by passcod** [comment]
Closing as it's over a year old... chime in if still a problem

**Comment by khepin** [comment]
Don't have that use case anymore ¯\_(ツ)_/¯

**Comment by qguv** [comment]
Hi, this is still a bug. It occurs when an enormous number of files change at once. Because watchexec builds a list of changed files and adds it to the environment of the child process as an environment variable, 

In #157, I'm proposing a workaround for cases like this.

**Comment by passcod** [comment]
THE ENVIRONMENT! Ahhhh! I'd never made the connection, but that makes complete sense. Thank you!
